# Basic Settings
UsePAM yes
Ciphers aes128-ctr,aes192-ctr,aes256-ctr
X11Forwarding no
PrintMotd no
PrintLastLog no
TCPKeepAlive yes
Compression no
UseDNS no

# Logging
LogLevel INFO

# Authentication
MaxAuthTries 3
LoginGraceTime 1m
PermitRootLogin yes
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
